name: perdiction_market_mvp
description: prediction market mvp 

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.4

environment:
  sdk: '>=2.18.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  get: ^4.6.5
  google_fonts: ^4.0.4
  figma_squircle: ^0.5.3
  cupertino_rounded_corners: ^2.1.1
  cached_network_image: ^3.2.3
  modal_bottom_sheet:
     git:
       url: https://github.com/followthemoney1/modal_bottom_sheet.git
       ref: main
       path: modal_bottom_sheet
  modals: ^1.0.0+1
  sticky_headers: ^0.3.0+2
  flutter_slidable: ^3.0.0
  http: ^0.13.5
  just_audio: ^0.9.31
  audioplayers: ^3.0.1
  provider: ^6.0.5
  video_player: ^2.5.2
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.18
  audio_session: ^0.1.13
  dio: ^5.1.1
  video_editor: ^2.4.0
  fraction: ^4.1.4
  helpers: ^1.2.0
  image_picker: ^0.8.7+3
  loading_gifs: ^0.3.0
  shimmer: ^2.0.0
  tiktoklikescroller: ^0.2.3
  contained_tab_bar_view: ^0.8.0
  sign_in_with_apple: ^4.3.0
  dot_navigation_bar: ^1.0.1+4
  glassmorphism_ui: ^0.3.0
  visibility_detector: ^0.4.0+2
  dismissible_page: ^1.0.2
  cupertino_onboarding: ^1.1.1
  local_hero: ^0.2.0
  connectivity_checker: ^1.1.0
  flutter_screenutil: ^5.8.2
  animations: ^2.0.7
  simple_ripple_animation: ^0.0.7
  flutter_nearby_connections: ^1.1.1
  device_info: ^2.0.3
  card_swiper: ^2.0.4
  like_button: ^2.0.5
  animated_gradient: ^0.0.2
  permission_handler: ^10.3.0
  flutter_screen_recording: ^2.0.8
  app_popup_menu: ^1.0.0
  popover: ^0.2.8+2
  pinput: ^3.0.1
  pull_to_refresh: ^2.0.0
  fluid_dialog: ^2.0.0
  settings_ui: ^2.0.2
  fl_chart: ^0.63.0
  readmore: ^2.2.0
  custom_sliding_segmented_control: ^1.7.5
  intl: ^0.18.1
  flutter_overlay_loader: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: 'NotoSansCJKr'
      fonts:
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Thin.otf
          weight: 100
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Light.otf
          weight: 200
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Regular.otf
          weight: 300
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Medium.otf
          weight: 400
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Bold.otf
          weight: 500
        - asset: assets/fonts/Noto_Sans_KR/NotoSansKR-Black.otf
          weight: 600
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

